# **# 468Page 스팸 메일 분류하기**
**202235203 고수호**




# **# 필요 라이브러리 임포트**

In [6]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

# **# 훈련 문서와 정답 레이블 정의**

In [7]:
docs = ['additional income',
        'best price',
        'big bucks',
        'cash bonus',
        'earn extra cash',
        'spring savings certificate',
        'valero gas marketing',
        'all domestic employees',
        'nominations for oct',
        'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])

# **# 각 문서 안의 단어들을 정수 인코딩**

In [8]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[15, 47], [45, 42], [22, 41], [9, 44], [2, 45, 9], [6, 41, 24], [38, 49, 15], [31, 37, 40], [36, 49, 49], [41, 49, 34]]


# **# 입력 시퀀스의 길이가 같도록 수정**

In [9]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[15 47  0  0]
 [45 42  0  0]
 [22 41  0  0]
 [ 9 44  0  0]
 [ 2 45  9  0]
 [ 6 41 24  0]
 [38 49 15  0]
 [31 37 40  0]
 [36 49 49  0]
 [41 49 34  0]]


# **# 이진 분류 신경망 모델 정의**

In [10]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


# **# 신경망 훈련 및 평가**

In [11]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


# **# 새로운 텍스트를 이용하여 간단하게 테스트**

In [14]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
[[0.57052845]]
